# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ameland Freizeit Neuwied
email: info@ameland-freizeit.de
description: > # this means to ignore newlines until "baseurl:"
  Wie viele andere Gruppen auch, zieht es uns jedes Jahr zweimal nach Ameland.
  Im Sommer mit Kindern im Alter von 9-13 Jahren, mit Betreuerinnen und Betreuern und der Küchenmannschaft. 
baseurl: "" # the subpath of your site, e.g. /blog
lang: "de"
url: "http://localhost:4001" # the base hostname & protocol for your site
port: 4001
facebook_username: 

# Build settings
markdown: kramdown
relative_permalinks: false
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"


compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      bg: bg.svg
